---
el:
  admin:
    custom_emojis:
      batch_copy_error: 'Παρουσιάστηκε σφάλμα κατά την αντιγραφή ορισμένων από τα επιλεγμένα emoji: %{message}'
      batch_error: 'Παρουσιάστηκε σφάλμα: %{message}'
    settings:
      captcha_enabled:
        desc_html: Αυτό βασίζεται σε εξωτερικά σκριπτάκια από το hCaptcha, όπου μπορεί να υπάρχει ανησυχία πέρι ασφάλειας και ιδιωτικότητας. Επιπρόσθετα, <strong> μπορεί να κάνει τη διαδικασία εγγραφής πολύ λιγότερο προσβάσιμη για κάποια άτομα (ειδικά αυτά με αναπηρίες)</strong>. Για αυτούς τους λόγους, παρακαλούμε σκεφτείτε άλλου τρόπους εγγραφής όπως με αποδοχή ή με πρόσκληση.
        title: Να απαιτείται από νέους χρήστες να λύσουν ένα CAPTCHA για να επιβεβαιώσουν τον λογαριασμό τους
      hide_followers_count:
        desc_html: Να μην εμφανίζεται ο αριθμός ακολούθων στα προφίλ χρηστών
        title: Απόκρυψη αριθμού ακολούθων
      other:
        preamble: Διάφορες ρυθμίσεις του glitch-soc που δεν ταιριάζουν στις άλλες κατηγορίες.
        title: Άλλες
      outgoing_spoilers:
        title: Προειδοποίηση περιεχομένου για εξερχόμενα τουτς
      show_reblogs_in_public_timelines:
        desc_html: Εμφάνιση δημόσιων ενισχύσεων των δημόσιων τουτς σε τοπικές και δημόσιες ροές.
        title: Εμφάνιση ενισχύσεων σε δημόσιες ροές
      show_replies_in_public_timelines:
        desc_html: Εκτός από τις δημόσιες αυτοαπαντήσεις (νήματα), εμφανίζονται δημόσιες απαντήσεις σε τοπικές και δημόσιες ροές.
        title: Εμφάνιση απαντήσεων σε δημόσιες ροές
      trending_status_cw:
        desc_html: Όταν είναι ενεργοποιημένες οι αναρτήσεις σε τάση, επιτρέπει τις αναρτήσεις με προειδοποιήσεις περιεχομένου να είναι κατάλληλες για τάση. Οι αλλαγές σε αυτήν τη ρύθμιση δεν είναι αναδρομικές.
        title: Να επιτρέπονται αναρτήσεις με προειδοποιήσεις περιεχομένου (CW) για τάση
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: Και ομοίως για το glitch-soc!
  auth:
    captcha_confirmation:
      hint_html: Απλώς ένα βήμα ακόμη! Για να επιβεβαιώσεις τον λογαριασμό σου, αυτός ο διακομιστής απαιτεί να λύσεις ένα CAPTCHA. Μπορείς να <a href="/about/more">επικοινωνήσεις με τον διαχειριστή του διακομιστή</a> αν έχεις ερωτήσεις ή χρειάζεσαι βοήθεια με την επιβεβαίωση του λογαριασμού σου.
      title: Επαλήθευση χρήστη
  generic:
    use_this: Χρησιμοποιήστε αυτό
