---
en:
  admin:
    action_logs:
      action_types:
        create_registration_filter: Create Registration Text Filter
        destroy_registration_filter: Destroy Registration Text Filter
        update_registration_filter: Update Registration Text Filter
      actions:
        create_registration_filter_html: "%{name} blocked registrations with request text matching %{target}"
        destroy_registration_filter_html: "%{name} unblocked registrations with request text matching %{target}"
        update_registration_filter_html: "%{name} updated registration filter blocking request text matching %{target}"
    custom_emojis:
      batch_copy_error: 'An error occurred while copying some of the selected emoji: %{message}'
      batch_error: 'An error occurred: %{message}'
      category_hint: Optional. Assign the emoji to a category.
      visible_in_picker: Show in emoji picker
      visible_in_picker_hint: Makes this emoji available in the emoji picker and API.
    instances:
      moderation:
        suspended: Suspended
    registration_filters:
      add_new: Add new filter
      created_msg: Registration text filter successfully created!
      delete: Delete
      description_html: Registration text filters allow you to automatically reject new user registrations based on their invite request text, that is their response to the “Why do you want to join?” prompt. This can be used to cut down on registration spam.
      destroyed_msg: Registration text filter successfully destroyed!
      edit:
        title: Edit registration text filter
      empty: No registration text filter found.
      new:
        create: Create registration text filter
        title: New registration text filter
      phrase: Keyword, phrase or regular expression
      phrase_hint: Forbid registration of new users whose answer to the “Why do you want to join?” prompt contains text that matches this keyword, phrase or regular expression.
      text: Text
      title: Registration text filters
      type:
        title: Filter type
      types:
        regexp: Regular Expression
        regexp_hint: Use regular expressions if you want to filter registrations featuring more advanced patterns.
        text: Simple text
        text_hint: Use this for simple recurring keywords and if you do not know regular expressions.
      updated_msg: Registration text filter successfully updated!
    roles:
      privileges:
        bypass_invite_limits: Bypass invite restrictions
        bypass_invite_limits_description: Allows users to create unlimited invites with unlimited uses
    settings:
      captcha_enabled:
        desc_html: This relies on external scripts from hCaptcha, which may be a security and privacy concern. In addition, <strong>this can make the registration process significantly less accessible to some (especially disabled) people</strong>. For these reasons, please consider alternative measures such as approval-based or invite-based registration.<br>Users that have been invited through a limited-use invite will not need to solve a CAPTCHA
        title: Require new users to solve a CAPTCHA to confirm their account
      default_norss:
        desc_html: Affects all users who have not changed this setting themselves
        title: Opt users out of having an RSS feed of their public toots by default
      default_show_application:
        desc_html: Affects all users who have not changed this setting themselves
        title: Disclose application used to send toots
      discovery:
        rss: RSS
        search: Search
      flavour_and_skin:
        title: Flavour and skin
      hide_followers_count:
        desc_html: Do not show followers count on user profiles
        title: Hide followers count
      other:
        preamble: Various glitch-soc settings not fitting in other categories.
        title: Other
      outgoing_spoilers:
        desc_html: When federating toots, add this content warning to toots that do not have one. It is useful if your server is specialized in content other servers might want to have under a Content Warning. Media will also be marked as sensitive.
        title: Content warning for outgoing toots
      show_reblogs_in_public_timelines:
        desc_html: Show public boosts of public toots in local and public timelines.
        title: Show boosts in public timelines
      show_replies_in_public_timelines:
        desc_html: In addition to public self-replies (threads), show public replies in local and public timelines.
        title: Show replies in public timelines
      trending_status_cw:
        desc_html: When trending toots are enabled, allow toots with Content Warnings to be eligible. Changes to this setting are not retroactive.
        title: Allow toots with Content Warnings to trend
      trending_status_sensitive:
        desc_html: When trending toots are enable, allow toots with sensitive media to be elibible. Changes to this setting are not retroactive.
        title: Allow toots with sensitive media to trend
    statuses:
      reactions: Reactions
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: And likewise for glitch-soc!
    toot_layout: Toot layout
  auth:
    captcha_confirmation:
      hint_html: Just one more step! To confirm your account, this server requires you to solve a CAPTCHA. You can <a href="/about/more">contact the server administrator</a> if you have questions or need assistance with confirming your account.
      title: User verification
  filters:
    instance_filter:
      title: Hidden by moderators
  generic:
    use_this: Use this
  invites:
    errors:
      daily_limit_reached: Daily limit of created invites reached
      limit_reached: Maximum number of active invites reached
    table:
      comment: Comment
  notification_mailer:
    reaction:
      body: "%{name} reacted to your toot:"
      subject: "%{name} reacted to your toot"
      title: New reaction
  regex_validator:
    invalid_regexp: 'error parsing regular expression: %{error}'
  settings:
    flavours: Flavours
  sounds:
    default: Boop
    laser: Laser
  users:
    invalid_invite_request_text: This text includes forbidden words or expressions
