---
ja:
  admin:
    custom_emojis:
      batch_copy_error: '選択したいくつかの絵文字のコピー中にエラーが発生しました: %{message}'
      batch_error: 'エラーが発生しました: %{message}'
    settings:
      captcha_enabled:
        desc_html: |-
          これはhCaptchaからの外部スクリプトに依存しており、セキュリティやプライバシー上の懸念となり得ます。
          さらに、<strong>この方法では、一部の人々（特に障害のある方）にとって登録プロセスが著しく利用しにくくなる可能性があります</strong>。
          これらの理由から、承認制や招待制といった代替手段を検討することをお勧めします。
        title: 新規ユーザーのアカウント承認にCHAPCHAを要求する
      flavour_and_skin:
        title: フレーバーとスキン
      hide_followers_count:
        desc_html: プロフィールページのフォロワー数を見られないようにします
        title: フォロワー数を隠す
      other:
        preamble: 他のカテゴリに該当しない多様なglitch-socの設定。
        title: その他
      outgoing_spoilers:
        desc_html: トゥートが連合される際、閲覧注意としてマークされていないトゥートにこの警告が追加されます。これはあなたのインスタンスが他のインスタンスに警告をして欲しいとされる投稿に特化している場合に便利です。 メディアは閲覧注意にマークされます。
        title: 発信するトゥートへの警告
      show_reblogs_in_public_timelines:
        desc_html: ローカルタイムラインと連合タイムラインに公開投稿のブーストを表示します
        title: 公開タイムラインにブーストを表示
      show_replies_in_public_timelines:
        desc_html: 自分への公開投稿の返信に加えて、すべての公開投稿の返信をローカルタイムラインと連合タイムラインに表示します。
        title: 公開タイムラインに返信を表示
      trending_status_cw:
        desc_html: トレンド投稿が有効な場合、コンテンツワーニング付きの投稿がトレンドに掲載されるのを許可します。この設定の変更は遡及的ではありません。
        title: 閲覧注意付きの投稿がトレンドに載るのを許可する
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: そしてglitch-socへも同様に！
  auth:
    captcha_confirmation:
      hint_html: あと一歩です！アカウントを承認するには、このサーバーでCAPTCHAを解いていただく必要があります。アカウントの確定に関してご質問やサポートが必要な場合は、<a href="/about/more">サーバー管理者にご連絡ください</a>。
      title: ユーザー認証
  generic:
    use_this: これを使う
  settings:
    flavours: フレーバー
