---
nn:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        setting_default_language: Språket i innleggene deres kan oppdages automatisk, men det er ikke alltid nøyaktig
    labels:
      defaults:
        setting_default_content_type: Standardformat for innlegg
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Ren tekst
        setting_show_followers_count: Vis følgerantallet deres
        setting_skin: Tema
